### ISSUE TITLE
Starvation detector test failing intermittently

### ISSUE THREAD

**Issue by franciscolopezsancho** [akka/akka-diagnostics#15]
There is a Starvation detector test which execution is not deterministic, it fails in CI - not in local - sometimes with the following:
```
- should CompletableFuture.get *** FAILED *** (5 seconds, 410 milliseconds)
[info]       java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on CustomEventFilter(<function1>)
[info]       at akka.testkit.EventFilter.intercept(TestEventListener.scala:122)
[info]       at akka.diagnostics.StarvationDetectorSpec.$anonfun$new$7(StarvationDetectorSpec.scala:102)
[info]       at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]       at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]       at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]       at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]       at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]       at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[info]       at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]       at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]       at akka.diagnostics.AkkaSpec.withFixture(AkkaSpec.scala:95)
[info]       at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
[info]       at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
[info]       at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info]       at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
[info]       at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:1067)
[info]       at akka.diagnostics.AkkaSpec.runTest(AkkaSpec.scala:95)
[info]       at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
[info]       at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
[info]       at scala.collection.immutable.List.foreach(List.scala:333)
[info]       at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]       at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[info]       at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[info]       at scala.collection.immutable.List.foreach(List.scala:333)
[info]       at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]       at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[info]       at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[info]       at scala.collection.immutable.List.foreach(List.scala:333)
[info]       at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]       at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[info]       at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[info]       at scala.collection.immutable.List.foreach(List.scala:333)
[info]       at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]       at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
[info]       at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[info]       at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
[info]       at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
[info]       at akka.diagnostics.AkkaSpec.runTests(AkkaSpec.scala:95)
[info]       at org.scalatest.Suite.run(Suite.scala:1124)
[info]       at org.scalatest.Suite.run$(Suite.scala:1106)
[info]       at akka.diagnostics.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:95)
[info]       at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
[info]       at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
[info]       at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
[info]       at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1[187](https://github.com/akka/akka-diagnostics/actions/runs/3656334803/jobs/6178728677#step:6:188))
[info]       at akka.diagnostics.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:95)
[info]       at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]       at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]       at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]       at akka.diagnostics.AkkaSpec.run(AkkaSpec.scala:95)
[info]       at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]       at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[info]       at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[info]       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[info]       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[info]       at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by johanandren** [comment]
Do you have some more output? Does either of the two filter printlns turn up?

**Comment by franciscolopezsancho** [comment]
Let me see

**Comment by franciscolopezsancho** [comment]
I can see in some runs the following
```
Unexpected warning: 
Exceedingly long scheduling time on ExecutionContext Dispatcher[custom-affinity-dispatcher]. Starvation detector task was only executed after 901 ms which is longer than the warning threshold of 30 milliseconds. This might be a sign of thread, CPU, or dispatcher starvation. This can be caused by blocking calls, CPU overload, GC, or overlong work units. See the below information for hints about what could be the cause. Next warning will be shown in 10000 milliseconds.

Thread states (total 4 thread):   4 TIMED_WAITING
Stack traces:
  3 thread(s) in state: TIMED_WAITING java.base@17/java.lang.Thread.sleep(Native Method)
    app//akka.diagnostics.StarvationDetectorSpec.$anonfun$AntiPatterns$1(StarvationDetectorSpec.scala:155)
    app//akka.diagnostics.StarvationDetectorSpec$$Lambda$829/0x00000008011171a8.apply$mcV$sp(Unknown Source)
    app//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    app//scala.util.Try$.apply(Try.scala:210)
    app//akka.diagnostics.StarvationDetectorSpec.$anonfun$new$8(StarvationDetectorSpec.scala:81)
    app//akka.diagnostics.StarvationDetectorSpec$$Lambda$855/0x000000080111ded8.apply$mcV$sp(Unknown Source)
    app//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    app//scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
    app//scala.concurrent.Future$$$Lambda$856/0x000000080111e1b8.apply(Unknown Source)
    app//scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
    app//akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
    app//akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
    app//akka.dispatch.BatchingExecutor$BlockableBatch$$Lambda$768/0x00000008010f96b0.apply$mcV$sp(Unknown Source)
    app//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    app//scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
    app//akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)

Potential issue 'Thread.sleep': Thread.sleep blocks a thread. Use system.scheduler.scheduleOnce or akka.pattern.after to continue processing asynchronously after a delay.

  1 thread(s) in state: TIMED_WAITING java.base@17/jdk.internal.misc.Unsafe.park(Native Method)
    java.base@17/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:376)
    app//akka.dispatch.affinity.AffinityPool$IdleStrategy.idle(AffinityPool.scala:89)
    app//akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.executeNext$1(AffinityPool.scala:256)
    app//akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.runLoop$1(AffinityPool.scala:271)
    app//akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.run(AffinityPool.scala:282)
    java.base@17/java.lang.Thread.run(Thread.java:833)

Additionally, 0 threads reported an empty stack trace, and 0 threads were sleeping pool threads waiting for work.
[WARN] [01/18/2023 11:15:40.174] [StarvationDetector-Dispatcher[custom-affinity-dispatcher]] [akka.actor.ActorSystemImpl(StarvationDetectorSpec)] Exceedingly long scheduling time on ExecutionContext Dispatcher[custom-affinity-dispatcher]. Starvation detector task was only executed after 901 ms which is longer than the warning threshold of 30 milliseconds. This might be a sign of thread, CPU, or dispatcher starvation. This can be caused by blocking calls, CPU overload, GC, or overlong work units. See the below information for hints about what could be the cause. Next warning will be shown in 10000 milliseconds.

Thread states (total 4 thread):   4 TIMED_WAITING
Stack traces:
  3 thread(s) in state: TIMED_WAITING java.base@17/java.lang.Thread.sleep(Native Method)
    app//akka.diagnostics.StarvationDetectorSpec.$anonfun$AntiPatterns$1(StarvationDetectorSpec.scala:155)
    app//akka.diagnostics.StarvationDetectorSpec$$Lambda$829/0x00000008011171a8.apply$mcV$sp(Unknown Source)
    app//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    app//scala.util.Try$.apply(Try.scala:210)
    app//akka.diagnostics.StarvationDetectorSpec.$anonfun$new$8(StarvationDetectorSpec.scala:81)
    app//akka.diagnostics.StarvationDetectorSpec$$Lambda$855/0x000000080111ded8.apply$mcV$sp(Unknown Source)
    app//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    app//scala.concurrent.Future$.$anonfun$apply$1(Future.scala:678)
    app//scala.concurrent.Future$$$Lambda$856/0x000000080111e1b8.apply(Unknown Source)
    app//scala.concurrent.impl.Promise$Transformation.run(Promise.scala:467)
    app//akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
    app//akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
    app//akka.dispatch.BatchingExecutor$BlockableBatch$$Lambda$768/0x00000008010f96b0.apply$mcV$sp(Unknown Source)
    app//scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
    app//scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
    app//akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)

Potential issue 'Thread.sleep': Thread.sleep blocks a thread. Use system.scheduler.scheduleOnce or akka.pattern.after to continue processing asynchronously after a delay.

  1 thread(s) in state: TIMED_WAITING java.base@17/jdk.internal.misc.Unsafe.park(Native Method)
    java.base@17/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:376)
    app//akka.dispatch.affinity.AffinityPool$IdleStrategy.idle(AffinityPool.scala:89)
    app//akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.executeNext$1(AffinityPool.scala:256)
    app//akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.runLoop$1(AffinityPool.scala:271)
    app//akka.dispatch.affinity.AffinityPool$AffinityPoolWorker.run(AffinityPool.scala:282)
    java.base@17/java.lang.Thread.run(Thread.java:833)

Additionally, 0 threads reported an empty stack trace, and 0 threads were sleeping pool threads waiting for work.
[info]     - should Socket connect *** FAILED *** (6 seconds, 136 milliseconds)
[info]       java.lang.AssertionError: timeout (3 seconds) waiting for 1 messages on CustomEventFilter(<function1>)
[info]       at akka.testkit.EventFilter.intercept(TestEventListener.scala:122)
[info]       at akka.diagnostics.StarvationDetectorSpec.$anonfun$new$7(StarvationDetectorSpec.scala:[102](https://github.com/akka/akka-diagnostics/actions/runs/3941347705/jobs/6758143645#step:6:103))
[info]       at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]       at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]       at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:[104](https://github.com/akka/akka-diagnostics/actions/runs/3941347705/jobs/6758143645#step:6:105))
[info]       at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]       at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]       at org.scalatest.WordSpecLike$$anon$3.apply(WordSpecLike.scala:1075)
[info]       at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]       at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]       at akka.diagnostics.AkkaSpec.withFixture(AkkaSpec.scala:95)
[info]       at org.scalatest.WordSpecLike.invokeWithFixture$1(WordSpecLike.scala:1073)
[info]       at org.scalatest.WordSpecLike.$anonfun$runTest$1(WordSpecLike.scala:1085)
[info]       at org.scalatest.SuperEngine.runTestImpl(Engine.scala:286)
[info]       at org.scalatest.WordSpecLike.runTest(WordSpecLike.scala:1085)
[info]       at org.scalatest.WordSpecLike.runTest$(WordSpecLike.scala:[106](https://github.com/akka/akka-diagnostics/actions/runs/3941347705/jobs/6758143645#step:6:107)7)
[info]       at akka.diagnostics.AkkaSpec.runTest(AkkaSpec.scala:95)
[info]       at org.scalatest.WordSpecLike.$anonfun$runTests$1(WordSpecLike.scala:1144)
[info]       at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:393)
[info]       at scala.collection.immutable.List.foreach(List.scala:333)
[info]       at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]       at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[info]       at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[info]       at scala.collection.immutable.List.foreach(List.scala:333)
[info]       at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]       at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[info]       at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[info]       at scala.collection.immutable.List.foreach(List.scala:333)
[info]       at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]       at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:370)
[info]       at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:407)
[info]       at scala.collection.immutable.List.foreach(List.scala:333)
[info]       at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:381)
[info]       at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:376)
[info]       at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:458)
[info]       at org.scalatest.WordSpecLike.runTests(WordSpecLike.scala:1144)
[info]       at org.scalatest.WordSpecLike.runTests$(WordSpecLike.scala:1143)
[info]       at akka.diagnostics.AkkaSpec.runTests(AkkaSpec.scala:95)
[info]       at org.scalatest.Suite.run(Suite.scala:1124)
[info]       at org.scalatest.Suite.run$(Suite.scala:[110](https://github.com/akka/akka-diagnostics/actions/runs/3941347705/jobs/6758143645#step:6:111)6)
[info]       at akka.diagnostics.AkkaSpec.org$scalatest$WordSpecLike$$super$run(AkkaSpec.scala:95)
[info]       at org.scalatest.WordSpecLike.$anonfun$run$1(WordSpecLike.scala:1189)
[info]       at org.scalatest.SuperEngine.runImpl(Engine.scala:518)
[info]       at org.scalatest.WordSpecLike.run(WordSpecLike.scala:1189)
[info]       at org.scalatest.WordSpecLike.run$(WordSpecLike.scala:1187)
[info]       at akka.diagnostics.AkkaSpec.org$scalatest$BeforeAndAfterAll$$super$run(AkkaSpec.scala:95)
[info]       at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
[info]       at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]       at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]       at akka.diagnostics.AkkaSpec.run(AkkaSpec.scala:95)
[info]       at org.scalatest.tools.Framework.org$scalatest$tools$Framework$$runSuite(Framework.scala:317)
[info]       at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:510)
[info]       at sbt.ForkMain$Run.lambda$runTest$1(ForkMain.java:413)
[info]       at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[info]       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:[113](https://github.com/akka/akka-diagnostics/actions/runs/3941347705/jobs/6758143645#step:6:114)6)
[info]       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[info]       at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by johanandren** [comment]
The `Unexpected warning` is from that filter

**Comment by johanandren** [comment]
So detector hits but in a different way, because of slow CI machine perhaps?

**Comment by johanandren** [comment]
BTW it's good to link to the failure log line in gh actions for easier detective work with failures like this.

**Comment by franciscolopezsancho** [comment]
What I don't understand is why is logging that the potential issue could be sleep. It must be looking at another thread trace. 
Although I think you are right on that the slow CI machine is probably the culprit. I run twice 100 tests on a row in my machine without a single error.

**Comment by johanandren** [comment]
Maybe it is leaking from one of the other tests? Just verifying that things are logged and moving on rather than making sure the blocking task they test has completed first?

**Comment by franciscolopezsancho** [comment]
Good idea 👍 . I'll try to follow each task to see when - and in which thread - they start and finish.

**Comment by franciscolopezsancho** [comment]
fixed in https://github.com/akka/akka-diagnostics/pull/36
