### ISSUE TITLE
Failed: StarvationDetectorSpec

### ISSUE THREAD

**Issue by johanandren** [akka/akka-diagnostics#63]
https://github.com/akka/akka-diagnostics/actions/runs/6744015799/job/18333009668

```
[info]   - should not log a warning if the dispatcher is busy for an amount of small non-blocking tasks *** FAILED *** (2 seconds, 201 milliseconds)
[info]     java.lang.AssertionError: received 1 excess messages on WarningFilter(None,Left(Exceedingly long scheduling time on ExecutionContext),false)
[info]     at akka.testkit.EventFilter.intercept(TestEventListener.scala:124)
[info]     at akka.diagnostics.StarvationDetectorSpec.$anonfun$new$12(StarvationDetectorSpec.scala:148)
```

**Comment by johanandren** [comment]
Seeing this pretty consistently now.
